// SPDX-License-Identifier: MIT
#include "module_fips.h"
#include "ctr_drbg.h"
#include <string.h>
#include <stdlib.h>
#include <stdatomic.h>

// DRBG KAT vectors header (auto-generated by Makefile 'prepare_kat' if placeholder)
#include "kat90a_vectors.h"

static atomic_int g_inited = 0;
static atomic_int g_error  = 0;
static atomic_int g_fips_mode = 0;

static int str_eq(const char* a, const char* b){
    if (!a || !b) return 0;
    while (*a && *b){ if (*a != *b) return 0; a++; b++; }
    return *a == *b;
}

static int selftest_drbg_kat(void) {
    rt_ctr_drbg d;
    if (rt_ctr_drbg_instantiate_no_df(&d, rt_kat_seed_0) != 0) return -1;
    uint8_t out[sizeof rt_kat_out0];
    if (rt_ctr_drbg_generate_all(&d, out, sizeof out) != 0) return -1;
    int ok = (memcmp(out, rt_kat_out0, sizeof rt_kat_out0) == 0);
    rt_ctr_drbg_uninstantiate(&d);
    return ok ? 0 : -1;
}

int rt_module_init(void) {
    int expected = 0;
    if (!atomic_compare_exchange_strong(&g_inited, &expected, 1)) {
        return atomic_load(&g_error) ? -1 : 0;
    }
    const char* env = getenv("RT_FIPS_MODE");
    if (env && (str_eq(env,"1") || str_eq(env,"on") || str_eq(env,"true"))) {
        atomic_store(&g_fips_mode, 1);
    }
#ifdef FIPS_MODE
    atomic_store(&g_fips_mode, 1);
#endif
    if (atomic_load(&g_fips_mode)) {
        if (selftest_drbg_kat() != 0) { atomic_store(&g_error, 1); return -1; }
    }
    return 0;
}

int rt_module_is_error(void) {
    return atomic_load(&g_error);
}

void rt_module_force_fips_mode(int on) {
    atomic_store(&g_fips_mode, on ? 1 : 0);
}
