name: ci

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y clang lld fasm dieharder pkg-config

      - name: Build
        env:
          CFLAGS: "-O3 -march=native -maes -mrdseed -fPIC"
        run: |
          make V=1

      - name: Selftest (power-up KAT)
        run: ./build/selftest

      # Smoke test only (não deixa o CI vermelho se o dieharder quiser mais amostra)
      - name: Dieharder smoke
        run: ./build/stream_randomtoad | head -c 33554432 | dieharder -g 200 -a -k 2 || true

      - name: Install + pkg-config check
        run: |
          sudo make install
          pkg-config --modversion randomtoad
          echo '#include <randomtoad/ctr_drbg.h>\nint main(){return 0;}' > /tmp/t.c
          clang $(pkg-config --cflags randomtoad) /tmp/t.c $(pkg-config --libs randomtoad) -fuse-ld=lld -o /tmp/t
