name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-selftest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps (clang, lld, fasm, dieharder)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            clang lld make fasm dieharder

      - name: Build (default)
        working-directory: ./src
        env:
          CFLAGS: "-O3 -march=native -maes -mrdseed"
        run: |
          make -j"$(nproc)"

      - name: Run selftest (expected: SELFTEST: OK)
        working-directory: ./src
        run: |
          set -e
          ./build/selftest | tee selftest.log
          grep -q "SELFTEST: OK" selftest.log

      - name: Build (FIPS mode)
        working-directory: ./src
        env:
          CFLAGS: "-O3 -march=native -maes -mrdseed"
        run: |
          make clean
          make -j"$(nproc)" fips

      - name: Run selftest (FIPS mode)
        working-directory: ./src
        run: |
          set -e
          RT_FIPS_MODE=1 ./build/selftest | tee selftest_fips.log
          grep -q "SELFTEST: OK" selftest_fips.log

      - name: Dieharder smoke (selected tests, short)
        working-directory: ./src
        continue-on-error: true   # não falha o pipeline se não passar/instalar
        timeout-minutes: 5
        run: |
          set -e
          # Testes leves: birthdays(0), operm5(1), rank_32x32(2), monobit(15)
          # -p 3 reduz psamples; -g 200 lê da stdin (stream_randomtoad)
          ./build/stream_randomtoad | dieharder -g 200 -d 0 -d 1 -d 2 -d 15 -p 3 | tee dieharder_smoke.log

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: randomtoad-build-and-logs
          path: |
            src/build/**
            src/selftest.log
            src/selftest_fips.log
            src/dieharder_smoke.log
